import matplotlib.pyplot as plt
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
from matplotlib import animation
import sys
sys.path.insert(0, '')
from src.load import read_graph
'''
This file takes as input a .csv file generated by the graph_influence.py 
script and produces a plot in three dimensions showing the relationship/correlation between the three objective functions.


'''

def plot(x2,y2,z2):
    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(8,3))
    fig.suptitle("IC", size=16)

    ax1.scatter(z2,x2)
    ax1.xaxis.set_ticks(np.arange(0,max(z2), 5))
    ax1.yaxis.set_ticks(np.arange(0, max(x2), 0.5))
    ax1.set_ylabel("Nodes")

    ax1.set_xlabel("Influence")
    fig.suptitle("IC", size=16)
    
    ax2.scatter(y2,x2)
    ax2.yaxis.set_ticks(np.arange(0,max(x2), 0.5))
    ax2.xaxis.set_ticks(np.arange(0, 100, 10))
    
    ax2.set_ylabel("Nodes")
    ax3.scatter(z2,y2)
    ax3.xaxis.set_ticks(np.arange(0,100, 5))
    ax3.yaxis.set_ticks(np.arange(0, max(y2)+2, 1))
    ax3.set_ylabel("Nodes")

    ax3.set_xlabel("")
    ax2.set_xlabel("Communities")

    ax1.set_box_aspect(1)
    ax2.set_box_aspect(1)
    ax3.set_box_aspect(1)
    fig.tight_layout()
    plt.show()
if __name__ == '__main__':
    
    filename = "graph_SBM_small_TRUE-4-k25-p0-LT-best_hv.csv"
    graph = "scale_graphs/graph_SBM_small.txt_TRUE-4.txt"

    G = read_graph(graph)
    N = G.number_of_nodes()
    my_degree_function = G.degree   
    mean = []
    for item in G:
        mean.append(my_degree_function[item])

    print(np.mean(mean))

    df = pd.read_csv(filename, sep=",")

    x=  df["n_nodes"]
    y = df["communities"]
    z = df["influence"]
    time = df["time"]
    std = df["std"] / N
    for i in range(len(z)):
        z[i] = (z[i]/N) * 100
        x[i] = (x[i]/N) * 100
        #y[i] = (y[i]/N) * 100
    
    #plot(x,y,z)

    filename = "graph_SBM_small_TRUE-2-k50-p0-LT-best_hv.csv"
    graph = "scale_graphs/graph_SBM_small.txt_TRUE-2.txt"

    G = read_graph(graph)
    N = G.number_of_nodes()
    my_degree_function = G.degree   
    mean = []
    for item in G:
        mean.append(my_degree_function[item])

    print(np.mean(mean))
    df = pd.read_csv(filename, sep=",")

    x0= df["n_nodes"].to_list()
    y0 = df["communities"].to_list()
    z0 = df["influence"].to_list()
    time0 = df["time"]
    std0 = df["std"] / N 

    for i in range(len(z0)):
        z0[i] = (z0[i]/N) * 100
        x0[i] = (x0[i]/N) * 100
        #y0[i] = (y0[i]/N) * 100

    #plot(x0,y0,z0)

    filename = "graph_SBM_small_TRUE-4-k25-p0.05-IC-best_hv.csv"
    graph = "scale_graphs/facebook_combined.txt_TRUE-2.txt"

    G = read_graph(graph)
    N = G.number_of_nodes()
    my_degree_function = G.degree   
    mean = []
    for item in G:
        mean.append(my_degree_function[item])

    print(np.mean(mean))
    df = pd.read_csv(filename, sep=",")

    x1= df["n_nodes"]
    y1 = df["communities"]
    z1 = df["influence"]
    time1 = df["time"]
    for i in range(len(z1)):
        z1[i] = (z1[i]/N) * 100
        x1[i] = (x1[i]/N) * 100
        #y1[i] = (y1[i]/N) * 100



    #plot(x1,y1,z1)

    filename = "graph_SBM_small-k100-p0-LT-best_hv.csv"  
    graph = "graphs/graph_SBM_small.txt"

    G = read_graph(graph)
    N = G.number_of_nodes()
    my_degree_function = G.degree   
    mean = []
    for item in G:
        mean.append(my_degree_function[item])

    print(np.mean(mean))

    df = pd.read_csv(filename, sep=",")

    x2= df["n_nodes"].to_list()
    y2 = df["communities"].to_list()
    z2 = df["influence"].to_list()
    time2= df["time"]
    std2 = df["std"] / N
    for i in range(len(z2)):
        z2[i] = (z2[i]/N) * 100
        x2[i] = (x2[i]/N) * 100
        #y2[i] = (y2[i]/N) * 100

    #plot(x2,y2,z2)

    plt.scatter(z,x,color="green",label="25%")
    plt.scatter(z0,x0,color="blue", label="50%")
    #plt.scatter(z1,x1,color="orange",label="75%")
    plt.scatter(z2,x2,color="red",label="100%")
    plt.title('SBM LT model')
    plt.xlabel('% Influenced Nodes')
    plt.ylabel('% Nodes as seed set')
    plt.legend()
    plt.xlim(0,100)
    plt.show()
    plt.cla()

    #plt.scatter(y,x,color="green",label="scale pop/offspring")
    #plt.scatter(z0,x0,color="blue", label="original pop/offspring")
    plt.scatter(y,x,color="green",label="25%")
    plt.scatter(y0,x0,color="blue", label="50%")
    #plt.scatter(z1,x1,color="orange",label="75%")
    plt.scatter(y2,x2,color="red",label="100%")
    plt.title('SBM LT model')
    plt.xlabel('Communities')
    plt.ylabel('% Nodes as seed set')
    plt.legend()
    plt.show()
    plt.cla()

    plt.scatter(z,y,color="green",label="25%")
    plt.scatter(z0,y0,color="blue", label="50%")
    #plt.scatter(z1,x1,color="orange",label="75%")
    plt.scatter(z2,y2,color="red",label="100%")
    plt.title('SBM LT model')
    plt.xlabel('% Influenced Nodes')
    plt.ylabel('Communities')
    plt.legend()
    plt.xlim(0,100)
    plt.show()
    plt.cla()


    fig = plt.figure()
    ax = fig.add_subplot(projection='3d')
    ax.scatter(x, y, z, marker='o', color="green")
    ax.scatter(x0, y0, z0, marker='o', color="blue")
    ax.scatter(x2, y2, z2, marker='o', color="red")
    plt.show()
    exit(0)
    fig, ax = plt.subplots(subplot_kw={"projection": "3d"})


    from matplotlib import cm
    fig = plt.figure()
    ax = Axes3D(fig)
    ax.plot_trisurf(x, y, z, color="green",linewidth=0.1,shade=True)
    ax.plot_trisurf(x0, y0, z0, color="blue",linewidth=0.1,shade=True)
    ax.plot_trisurf(x2, y2, z2, color="red",linewidth=0.1,shade=True)

    plt.show()
    exit(0)





    ## Time
    fig = plt.figure(1, figsize=(9, 6))

    ax = fig.add_subplot(111)

    data_plot = [time, time0, time2]

    bp = ax.boxplot(data_plot)
    plt.xticks([1, 2, 3], ['25%', '50%', 'Original Graph'])
    fig.suptitle('Time LT SBM')
    plt.show()
    plt.cla()
    plt.close()


    ## STD
    fig = plt.figure(1, figsize=(9, 6))
    # Create an axes instance
    ax = fig.add_subplot(111)

    # Create the boxplot
    data_plot = [std, std0, std2]
    bp = ax.boxplot(data_plot)
    fig.suptitle('STD LT SBM')
    plt.xticks([1, 2, 3], ['25%', '50%', 'Original Graph'])

    plt.show()

    