import matplotlib.pyplot as plt
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import matplotlib
import os
from matplotlib import animation
import sys
sys.path.insert(0, '')
from src.load import read_graph
'''
This file takes as input a .csv file generated by the graph_influence.py 
script and produces a plot in three dimensions showing the relationship/correlation between the three objective functions.


'''

if __name__ == '__main__':
    
    filename = "graph_SBM_small_scale_2-k50-p0.05-IC-communities.csv"  
    graph = "scale_graphs/graph_SBM_small_scale_2.txt"

    G = read_graph(graph)
    N = G.number_of_nodes()


    df = pd.read_csv(filename, sep=",")

    x1= df["n_nodes"].to_list()
    y1 = df["time"].to_list()
    z1 = df["influence"].to_list()

    for i in range(len(z1)):
        z1[i] = (z1[i]/N) * 100
        x1[i] = (x1[i]/N) * 100
    

    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(8,3))
    fig.suptitle("IC", size=16)

    ax1.scatter(z1,x1)
    ax1.xaxis.set_ticks(np.arange(0,max(z1), 5))
    ax1.yaxis.set_ticks(np.arange(0, max(x1), 0.5))
    ax1.set_ylabel("Nodes")

    ax1.set_xlabel("Influence")

    filename = "graph_SBM_small_scale_2-k50-p0.1-IC-communities.csv"  
    graph = "scale_graphs/graph_SBM_small_scale_2.txt"

    G = read_graph(graph)
    N = G.number_of_nodes()

    df = pd.read_csv(filename, sep=",")

    x1= df["n_nodes"]
    y1 = df["time"]
    z1 = df["influence"]

    for i in range(len(z1)):
        z1[i] = (z1[i]/N) * 100
        x1[i] = (x1[i]/N) * 100
    
    fig.suptitle("IC", size=16)
    ax2.scatter(z1,x1)
    ax2.xaxis.set_ticks(np.arange(0,max(z1)+5, 5))
    ax2.yaxis.set_ticks(np.arange(0, max(x1), 0.5))
    ax2.set_ylabel("Nodes")

    ax2.set_xlabel("Influence")



    filename = "graph_SBM_small-k100-p0.01-IC-communities.csv"  
    graph = "graphs/graph_SBM_small.txt"

    G = read_graph(graph)
    N = G.number_of_nodes()

    df = pd.read_csv(filename, sep=",")

    x1= df["n_nodes"]
    y1 = df["time"]
    z1 = df["influence"]

    for i in range(len(z1)):
        z1[i] = (z1[i]/N) * 100
        x1[i] = (x1[i]/N) * 100
    

    ax3.scatter(z1,x1)
    ax3.xaxis.set_ticks(np.arange(0,max(z1)+5, 5))
    ax3.yaxis.set_ticks(np.arange(0, max(x1), 0.5))
    ax3.set_ylabel("Nodes")

    ax3.set_xlabel("Influence")
    # ax2.scatter(y1, z1)
    # ax2.xaxis.set_ticks(np.arange(0, df["time"].max()+1, 1))
    # ax2.yaxis.set_ticks(np.arange(0,df["influence"].max()+250, 250))
    # ax2.set_xlabel("No Communities")

    # ax2.set_ylabel("Influence")
    
    # ax3.scatter(y1,x1)
    # ax3.yaxis.set_ticks(np.arange(0, df["n_nodes"].max()+1, 10))
    # ax3.xaxis.set_ticks(np.arange(0,df["time"].max()+1, 1))
    # ax3.set_xlabel("No Communities")

    # ax3.set_ylabel("Nodes")

    ax1.set_box_aspect(1)
    ax2.set_box_aspect(1)
    ax3.set_box_aspect(1)
    fig.tight_layout()
    #uncomment to save the plot in .png format
    #fn = str(os.path.basename(filename))
    #fn = fn.replace(".csv", "")
    #plt.savefig('gif/{}.png'.format(fn))
    plt.show()

    exit(0)

    filename = "facebook_combined_scale_2-k50-p0.0459030556566024-LT.csv.csv"

    df = pd.read_csv(filename, sep=",")

    x2= df["n_nodes"]
    y2 = df["influence"]
    #plt.scatter(x2, y2)
    print(max(y2))
    #plt.show()

    plt.cla()
    final = [z1,y2]
    plt.boxplot(final)
    plt.title("Influence")
    plt.xlabel("Graph")
    plt.ylabel("Influence")
    plt.xticks([1, 2], ['#C', 'without #C'])
    plt.show()  
    #uncomment to save the plot in .gif  and .mp4 format
    #save_video()